"""Agregar modelos para cambio de estado

Revision ID: b258d2e63107
Revises: 1bf9f3f663b7
Create Date: 2024-10-03 02:36:59.711006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b258d2e63107'
down_revision = '1bf9f3f663b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auditoria', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_hora', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('detalles', sa.Text(), nullable=True))
        batch_op.drop_column('fecha')
        batch_op.drop_column('detalle')

    with op.batch_alter_table('movimiento', schema=None) as batch_op:
        batch_op.add_column(
                sa.Column('estado_anterior_id', sa.Integer(), nullable=False)
                )
        batch_op.add_column(
                sa.Column('estado_nuevo_id', sa.Integer(), nullable=False)
                )
        batch_op.add_column(
                sa.Column('fecha_hora', sa.DateTime(), nullable=False)
                )
       # batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(
                'fk_movimiento_estado_anterior',
                'estado',
                ['estado_anterior_id'], 
                ['id']
                )
        batch_op.create_foreign_key(
                'fk_movimiento_estado_nuevo', 
                'estado',
                ['estado_nuevo_id'], 
                ['id']
                )
        batch_op.drop_column('estado_nuevo')
        batch_op.drop_column('estado_anterior')
        batch_op.drop_column('fecha')
        batch_op.drop_column('usuario_id')

    with op.batch_alter_table('notificacion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_hora', sa.DateTime(), nullable=False))
        batch_op.alter_column(
                'mensaje',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=250),
               existing_nullable=False
               )
        batch_op.drop_column('fecha')

    with op.batch_alter_table('producto', schema=None) as batch_op:
        batch_op.alter_column(
                'descripcion',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True
               )
        batch_op.drop_column('fecha_creacion')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('producto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_creacion', sa.DATETIME(), nullable=True))
        batch_op.alter_column('descripcion',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)

    with op.batch_alter_table('notificacion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha', sa.DATETIME(), nullable=True))
        batch_op.alter_column('mensaje',
               existing_type=sa.String(length=250),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)
        batch_op.drop_column('fecha_hora')

    with op.batch_alter_table('movimiento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usuario_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('fecha', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('estado_anterior', sa.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('estado_nuevo', sa.VARCHAR(length=50), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'usuario', ['usuario_id'], ['id'])
        batch_op.drop_column('fecha_hora')
        batch_op.drop_column('estado_nuevo_id')
        batch_op.drop_column('estado_anterior_id')

    with op.batch_alter_table('auditoria', schema=None) as batch_op:
        batch_op.add_column(sa.Column('detalle', sa.VARCHAR(length=500), nullable=True))
        batch_op.add_column(sa.Column('fecha', sa.DATETIME(), nullable=True))
        batch_op.drop_column('detalles')
        batch_op.drop_column('fecha_hora')

    # ### end Alembic commands ###
