"""Add RFID columns to Producto table

Revision ID: c4cc3a053099
Revises: b570529d9974
Create Date: 2024-11-05 12:46:51.832233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4cc3a053099'
down_revision = 'b570529d9974'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('producto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rfid_tag', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('ultimo_escaneo', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('ubicacion_actual', sa.String(length=100), nullable=True))
        batch_op.create_unique_constraint('uq_producto_rfid_tag', ['rfid_tag'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('producto', schema=None) as batch_op:
        batch_op.drop_constraint('uq_producto_rfid_tag', type_='unique')
        batch_op.drop_column('ubicacion_actual')
        batch_op.drop_column('ultimo_escaneo')
        batch_op.drop_column('rfid_tag')

    # ### end Alembic commands ###
